name: Submit new Provider
description: Submit a new OpenTofu Provider
title: "Provider: "
labels: ["provider", "submission"]
body:
  - type: input
    id: repository
    attributes:
      label: Provider Repository
      description: Path to a public GitHub repository following the pattern {owner}/terraform-provider-{name}, ex. opentofu/terraform-provider-aws
    validations:
      required: true
