name: Submit new Provider Signing Key
description: Submit a new OpenTofu Provider Signing Key
title: "Provider Key: "
labels: ["provider-key", "submission"]
body:
  - type: input
    id: namespace
    attributes:
      label: Provider Namespace
      description: GitHub Username or Organization that contains Providers
    validations:
      required: true
  - type: checkboxes
    id: public_membership
    attributes:
      label: Public Membership
      description: If this is for a GitHub organization, I have [made my membership in that organization public](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-your-membership-in-organizations/publicizing-or-hiding-organization-membership).
      options:
        - label: I have made my membership public
          required: true
  - type: textarea
    id: gpgkey
    attributes:
      label: Provider GPG Key
      description: Armoured public PGP key
