name: Validate Provider JSON

on:
  push:
    paths:
      - 'providers/**/*.json'
    branches:
      - 'provider-**'

jobs:
  validate-metadata-provider:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - uses: actions/setup-go@v5
        with:
          go-version-file: './src/go.mod'

      - name: Build validator
        working-directory: ./src
        run: |
          mkdir -p /tmp/validate
          go build -o /tmp/validate/run ./cmd/validate/main.go
          chmod +x /tmp/validate/run

      - name: List updated files
        id: updated
        uses: tj-actions/changed-files@v42
        with:
          files: providers/**/*.json

      - name: Validate JSON
        env:
          CHANGED_FILES: ${{ steps.updated.outputs.all_changed_files }}
        run: |
          /tmp/validate/run provider "$CHANGED_FILES"
